github_id_ed25519: ENC[AES256_GCM,data:oHhlfnrM034i/KASryIIWnXD0Kwx9o8S+jEP4RmXgW3SSwoDLPjRSDf1awzr5Fr4kPtGYXEA/VsHoCiGufI9LttIoSvCR1c5CTmUHJiSwaO/ZlXQS8HFpZnx7dQztsAlTabCwtrb7vGcW7UrqDbq9RPZcD2UFXSmN/4kwBDGZFkIlNnBUnUmRvZBd/8e6B/M1SMUPhLBVWs8clmn06J0DjoBUd0olYg/2fuLN7nMC1pUtaqBA7/5WMER6eCrjFF0M2FPxz2XINXUEPexnyAbP/zvaekQ9+NpWtlBbbp87KQOGoV9b2PA5z2mMGl34/QvMq9XKwrleiO+PRH6C8nCFSkviwuPVDkB4KBIItRsisDX7CaUAJ00jtrwSL0NSwU/MA1Ck2VjvAGJLRu5ug2ZPBjFSvDix1j65VxCOAWMu8cwDrw2R7+qABJYgFh4m30fnxCbbOdq+EL1kjHs6yoMkt7eh6QzHu9GtZkvEYiFlGL0eFphhr2hcYNQVS9bUX13KGoe,iv:EbpJX6a4yaN8z9B4cfnDLbPGwZS+xiarY0n7L5WmEIk=,tag:Z2sLjTbhUw7dyjJTaF9YBg==,type:str]
amnezia_vpn_key: ENC[AES256_GCM,data:hMNdAGX7hv7go/2D7J0SqBQheETNHvaYnPMTGGKNGcN90uaW+fjWST79LmWXFqfN9bsygHJ8oFV7wXlfjkvFUSe4Ep5aqgD4wlLdtdQqYubq8+e4MQ3RMzodMM9P8RJzDjGzEimRQVIBmHov7vyyF+cbWLc+08gpT4qYI4YPFebD3a6MaGlsj0bMLhIYlklJT907RGvMovX+MjdFbH1nykz6cpbpHNUeJhhKlvVuMJN2jvdDdYRRLVEhP7646tZfqrGq5k+KsunKpukrLciKuWj4tDSV+9fdZxh9Rm7tV3j8fxkVlAcpInF+R0zotkiCrpdOyOJ9HJW9m4e/x9+keoO4ZvDyH3UjleqjeZLMmPeGepwr4zxmFxKXphzmLJwuxSgxfU/uTbZ+678fPeYQ1qYcoXlm7GyTbVAF6AxXrsqew8HZE8YZiZH57O/+Xxi+gzuCt1i2oTs1J6jjipJBC0K4RTF80FGS+4Enkx6gS4CS4+dJAHMo4MAH+G1O2lJ/4TEDN4I6Mv5nxHOlLBR5pk3M7IYSONEuEQ7w6zGnPjth5mAWgEUAiISbkkDA0dGrShM5pk31ZRvju/4UToWRakHjLTFOxfnrujK0CoUXWXzhcJmR4+q/mjncSkjTyZLTS7LGGI6xyWlZpttyZo5B2lxt9gV6Fmq9GkW2F+0Nws4x0rDfxCCdcHsE91TBj1bSjaStKtMrJZDEGFPDhgGp2UkWyqoiZJoEcl4Rr8fJQIgNE076IYRcLU2vmPGhhf94hlrREM+0x+WiU+SPg7hbTEVgKoIkCs8GJrRFtqWg40HjryPij6JwO7RUxEiE7dJTJwX/ZJVodX0veuDn9LcvMqkk50BiUqQhP1LiST+iJZLm0GpsHCO1rpeebq9wHiyS9nL9jE9sSt2OBBx25U5EmDQpzDlRXH63+KjH3XhJNusZ+ijrmoxC/8uVvN4RAGaboyIIeuqpHBa44eqqQBm+66p27vDTB1Dswhx35ZZfljAJsf6Ikw0JCaI6MkyNIbH1pGN2vtJfxNAnYMMSdjVjNdv50UmIfaLHYVO8jfViClzJjJq5DSl9+tU9vYKanFm0TKfavrzyT1SKf/OJBWM=,iv:5aAb3l7Mpwv0IrXNZwyxhF7xFEMVwmV6lgU67MIMPkQ=,tag:xSdnTbc793Yumti/thyNAQ==,type:str]
github_pat: ENC[AES256_GCM,data:i0wEx4wYisj+znR36iMjjnQDC079AnCkj0UY+3sx73E4RCweATZ9vdRXMg/2o0EwGJwm5yk9J0/0vo4xPQ2m5+2Ie/lv9/Cem7YvvZr2sNYT4kkqi6HQObiuhnMyAA==,iv:a4PrTyw7fmBJXdyH6y7U5dRR0QeSby00nQBK++1kgMU=,tag:yOBC21NOd7x/GFdcde8neQ==,type:str]
sops:
    age:
        - recipient: age1efmu87qgg6gw0knvdnszc34ucjhce0xaz9ukynx3y2z5xzj40edqhkvw3r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UjFjZE9ybWUyL2QveDIy
            ZFJ4YktpMjU4L2haaWlTNjJaK2dXOGNlN0RFClBya1YyWVUwNGZ2VzhyL0tIQmVN
            cnFPRG1rSkpGTzF3Wmp3V1RBR3ZPRU0KLS0tIHFYWWFzeE54Q1BUV1E5eis1ZG15
            Sk04cjA5aS95Y3pzZjlFempZeEtWL0kKZtXt8OdETqxVrYQgxJwqJOOXUPYe0WYq
            fOwal4ia9ZCItzfy1jpbxNxcxa7IEaTbq7Lcuv8pWlk+FMSKnVNtEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xycswvqjcgj6pxvu5880zuu9ck5fa3qf7hrunvulxwtalyf6qvwsfm7hqr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeFBMNnI3TG5CRjFkeVhO
            bGZmZXNaNXlaTmRGdUxKOFM0dE1ocDVoQUVRCkVvQ3E2cE4vTVZua1liandwTWhn
            R3d3UHoxTjBBMUlwVnk4aU1qeXBDY2sKLS0tIFYzZHFRcjhza29SUkJjcnlrWHVP
            V2VQZnFmYzZrNlljS2RjUUdxOVp2NGsK/DiNm5Bh1Ajf6SzgtANN7DzgyLBr4fKW
            L3ojIwNeSLkoO4Q/DXr9q+l4jDJVclF+Ch3QMvYzy0409M9glYMcpg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age190zxq9xhfj8d2zqyrsy7jn2cfz5t683e7ln2p0tym27pn06kwfsqvypjwp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQzBGM3dYQ3lGdlk0RCtD
            cTJUQUtzdjVpMUtGd29TOHhJUVJlamMrQ3c0CnF6djluTkZ1OEFnZXdxd2xYOGFO
            K2NIZVpUcHVNOE42MXJHSlFRZk9zVmMKLS0tIEhSODJQUVozbStodm1MM0Z1eWJ5
            aE9Xb1VFUGdGR2FPYjdJbTZQQlVJRlEKIn+7riZ11hIskApWovRFv7Ibatw08PR2
            wpfHUnKlrLoNOG1sHBxDFcNUHF4p+lyneRSBLAYLrdv02ufKG4j9/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-28T07:36:54Z"
    mac: ENC[AES256_GCM,data:AY7mL1HWiKZu6zuChvAxmuxtPG8Pq+PaYrAAQ5bMvDcCRlcd0T+f3bvrA4fqGKesYku4KNwUsvrIrYStfr8qwe4fRffkHubIe+9icFUFJXxRjtcfyA2PLJQAWtIdVKVApGW/cvd0eEu95ssmoehu8R5rKrN1QExPxDCSJ9dRrQk=,iv:II68S/5npDslB1/KMU0+6MVA9XaFy28YrqD8midEDbA=,tag:dYsAndxLPgN+KALlRbmyhg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
