github_id_ed25519: ENC[AES256_GCM,data:oHhlfnrM034i/KASryIIWnXD0Kwx9o8S+jEP4RmXgW3SSwoDLPjRSDf1awzr5Fr4kPtGYXEA/VsHoCiGufI9LttIoSvCR1c5CTmUHJiSwaO/ZlXQS8HFpZnx7dQztsAlTabCwtrb7vGcW7UrqDbq9RPZcD2UFXSmN/4kwBDGZFkIlNnBUnUmRvZBd/8e6B/M1SMUPhLBVWs8clmn06J0DjoBUd0olYg/2fuLN7nMC1pUtaqBA7/5WMER6eCrjFF0M2FPxz2XINXUEPexnyAbP/zvaekQ9+NpWtlBbbp87KQOGoV9b2PA5z2mMGl34/QvMq9XKwrleiO+PRH6C8nCFSkviwuPVDkB4KBIItRsisDX7CaUAJ00jtrwSL0NSwU/MA1Ck2VjvAGJLRu5ug2ZPBjFSvDix1j65VxCOAWMu8cwDrw2R7+qABJYgFh4m30fnxCbbOdq+EL1kjHs6yoMkt7eh6QzHu9GtZkvEYiFlGL0eFphhr2hcYNQVS9bUX13KGoe,iv:EbpJX6a4yaN8z9B4cfnDLbPGwZS+xiarY0n7L5WmEIk=,tag:Z2sLjTbhUw7dyjJTaF9YBg==,type:str]
sops:
    age:
        - recipient: age1efmu87qgg6gw0knvdnszc34ucjhce0xaz9ukynx3y2z5xzj40edqhkvw3r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UDFVeU4rdUZCMmVFcU1F
            anBVb1pjNVN4M25ZUm5sdWlhWmVxNVo5dFFNCmhVME9ESXhjZDd3SG5kRHA0TXJo
            dlg4ZSt3UktJVW1uUGkwV2xtZ1U3TFEKLS0tIHczeisyeXFXd3FSVEtrbFFSSnZO
            dWdBbHlxK01zK0cvNnl4VVV3YlpPU1kKnpCOlsSZN+Rkerc3icK0j8qMXO4LdgI2
            YcZbP4uPWVAip/uCsLfjMNilcBNqobQUChwxN11toEAUE6Hav1KOcA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xycswvqjcgj6pxvu5880zuu9ck5fa3qf7hrunvulxwtalyf6qvwsfm7hqr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvY0YrVWhnVzM0N0pPSUN2
            c2xDc1JCckQ0N0ZwYjdIMXM0TE1MS2dNNng0CnduYjBldWQ2RE5vcm5Ec0s2MXNh
            cDhQamI4eXFaeGxyb1RPM1Z6ZER2SncKLS0tIFB2bGppejEvWXVCWFdnZjBTZWJG
            V25URzB1ZEdmcUpPc0xUYjFCWGp6SzQKWlhKz4Jz1l6wDZFmwuNxXHt1kHQBToBE
            Ix4sDf/EeY/SsN46pCVQLDlakhD2IxZR4QyurNiTgZ7uCs5+rVzeZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-22T18:29:47Z"
    mac: ENC[AES256_GCM,data:BX/O+9WArM/I9ypvoDNHip///w701XxwFMcKE05hXLvuE3u9a9L3bN4wAFpAbxxDf/C+JfZL0bBxJqrgiYh6LkVCy/vT1RWSPpjEHWxeNP4LmO29jl2wjX+nRkXSjcA+7Ac8149G325Ruh2rC0FZibzZh8yiZ6CRl8hjgnTev1E=,iv:RU+NsSxiReGimAokKKz96NXUw98vaiqBF8JtQKVJSpg=,tag:VWciZ8mJQRFuPMQsyASawA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
